name: Pixelball
version: '${project.version}'
main: io.github.cats1337.pixelball.Pixelball
api-version: '1.20'
authors: [Cats1337, awesomepandapig, MarcusSlover]
description: Pixelball
commands:
  donationbb:
    description: Donation Bossbar Menu
